#!/usr/bin/env /bin/bash

set -e
source "$(dirname $0)/../.env"

TASK=$@

docker exec -it ${PROJECT_NAME}_node /bin/bash -c "\
umask g=rwx,u=rwx,o=rwx &&\
cd /var/www &&\
npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN} &&\
npm publish --access public"

