version: '3.9'

name: xml_editor_cmp

services:

  node:
    hostname: node
    container_name: ${PROJECT_NAME}_node
    build: services/node
    working_dir: /var/www
    command: tail -f /dev/null
    volumes:
      - type: bind
        source: ..
        target: /var/www
    ports:
      - 3333:3333
    networks:
      - mainnet

networks:
  mainnet:
    driver: bridge
