/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DropdownConfig, EditorFormattedTEI, EditorSettings, QuillInstance, TcsAnnotationFormValues, TcsBlankSpaceFormValues, TcsSelectEntry, TcsSettingsFormValues, TcsStructureFormValues, ToolbarConfig, UnionAbbreviationType, UnionDeletedRend, UnionEditorType, UnionHighlightedRend, UnionIcons, UnionLayoutType, UnionReconstructionReason, UnionStructureType, UnionUnclearReason } from "./lib/types";
export { DropdownConfig, EditorFormattedTEI, EditorSettings, QuillInstance, TcsAnnotationFormValues, TcsBlankSpaceFormValues, TcsSelectEntry, TcsSettingsFormValues, TcsStructureFormValues, ToolbarConfig, UnionAbbreviationType, UnionDeletedRend, UnionEditorType, UnionHighlightedRend, UnionIcons, UnionLayoutType, UnionReconstructionReason, UnionStructureType, UnionUnclearReason } from "./lib/types";
export namespace Components {
    interface TcsAnnotationForm {
        "isValid": () => Promise<boolean>;
    }
    interface TcsBlankSpaceForm {
        "isValid": () => Promise<boolean>;
    }
    interface TcsButton {
        "active"?: boolean;
        "disabled"?: boolean;
        "display"?: 'slim'|'default';
        "icon"?: UnionIcons;
        "iconOnly"?: boolean;
        "iconPosition"?: 'leading' | 'trailing';
        "outlined"?: boolean;
        "rotateOnActive"?: boolean;
        "rounded"?: boolean;
        "slimText"?: string;
        "stretched"?: boolean;
        "variation"?: 'default';
    }
    interface TcsDropdown {
        "close": () => Promise<void>;
        "config": DropdownConfig;
        "disabled": boolean;
        "display"?: 'slim'|'default';
        "open": () => Promise<void>;
        "slimText"?: string;
    }
    interface TcsEditor {
        "getFormattedTEI": () => Promise<EditorFormattedTEI>;
        "getQuillInstances": () => Promise<Map<UnionEditorType, QuillInstance>>;
        "getSettings": () => Promise<EditorSettings>;
        "lock": () => Promise<void>;
        "setFormattedTEI": (tei: EditorFormattedTEI) => Promise<void>;
        "settings": EditorSettings;
        "toolbarConfig": ToolbarConfig;
        "unlock": () => Promise<void>;
    }
    interface TcsIcon {
        "icon": UnionIcons;
        "library"?: string;
        "viewBox"?: string;
    }
    interface TcsPopup {
        "closePopup": () => Promise<void>;
        "openPopup": () => Promise<void>;
        "setContent": (content: string) => Promise<void>;
    }
    interface TcsSelect {
        "entries": TcsSelectEntry[];
        "getValue": () => Promise<string | number>;
        "inputId": string;
        "inputName": string;
        "isValid": () => Promise<boolean>;
        "placeholder"?: string;
        "required"?: boolean;
        "setValue": (value: string) => Promise<void>;
    }
    interface TcsSettingsForm {
        "defaultValues": TcsSettingsFormValues;
        "isValid": () => Promise<boolean>;
    }
    interface TcsStructureForm {
        "isValid": () => Promise<boolean>;
    }
    interface TcsTextfield {
        "allowedValues"?: (string|number)[];
        "defaultValue": string;
        "getValue": () => Promise<string>;
        "inputId": string;
        "inputName": string;
        "integer"?: boolean;
        "isValid": () => Promise<boolean>;
        "max"?: number;
        "min"?: number;
        "pattern"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "setValue": (value: string) => Promise<void>;
        "type": 'text'|'password'|'number'|'email';
    }
    interface TcsToolbar {
        "config": ToolbarConfig;
        "disabled": boolean;
        "layoutType": UnionLayoutType;
        "locked": boolean;
        "textDirection": 'LTR'|'RTL';
        "viewRaw": boolean;
    }
    interface TcsVisualizer {
    }
}
export interface TcsAnnotationFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsAnnotationFormElement;
}
export interface TcsBlankSpaceFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsBlankSpaceFormElement;
}
export interface TcsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsButtonElement;
}
export interface TcsIconCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsIconElement;
}
export interface TcsSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsSelectElement;
}
export interface TcsSettingsFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsSettingsFormElement;
}
export interface TcsStructureFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsStructureFormElement;
}
export interface TcsTextfieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsTextfieldElement;
}
export interface TcsToolbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTcsToolbarElement;
}
declare global {
    interface HTMLTcsAnnotationFormElementEventMap {
        "formChange": TcsAnnotationFormValues;
        "formSubmit": TcsAnnotationFormValues;
    }
    interface HTMLTcsAnnotationFormElement extends Components.TcsAnnotationForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsAnnotationFormElementEventMap>(type: K, listener: (this: HTMLTcsAnnotationFormElement, ev: TcsAnnotationFormCustomEvent<HTMLTcsAnnotationFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsAnnotationFormElementEventMap>(type: K, listener: (this: HTMLTcsAnnotationFormElement, ev: TcsAnnotationFormCustomEvent<HTMLTcsAnnotationFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsAnnotationFormElement: {
        prototype: HTMLTcsAnnotationFormElement;
        new (): HTMLTcsAnnotationFormElement;
    };
    interface HTMLTcsBlankSpaceFormElementEventMap {
        "formChange": TcsBlankSpaceFormValues;
        "formSubmit": TcsBlankSpaceFormValues;
    }
    interface HTMLTcsBlankSpaceFormElement extends Components.TcsBlankSpaceForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsBlankSpaceFormElementEventMap>(type: K, listener: (this: HTMLTcsBlankSpaceFormElement, ev: TcsBlankSpaceFormCustomEvent<HTMLTcsBlankSpaceFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsBlankSpaceFormElementEventMap>(type: K, listener: (this: HTMLTcsBlankSpaceFormElement, ev: TcsBlankSpaceFormCustomEvent<HTMLTcsBlankSpaceFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsBlankSpaceFormElement: {
        prototype: HTMLTcsBlankSpaceFormElement;
        new (): HTMLTcsBlankSpaceFormElement;
    };
    interface HTMLTcsButtonElementEventMap {
        "clickButton": HTMLDivElement;
    }
    interface HTMLTcsButtonElement extends Components.TcsButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsButtonElementEventMap>(type: K, listener: (this: HTMLTcsButtonElement, ev: TcsButtonCustomEvent<HTMLTcsButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsButtonElementEventMap>(type: K, listener: (this: HTMLTcsButtonElement, ev: TcsButtonCustomEvent<HTMLTcsButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsButtonElement: {
        prototype: HTMLTcsButtonElement;
        new (): HTMLTcsButtonElement;
    };
    interface HTMLTcsDropdownElement extends Components.TcsDropdown, HTMLStencilElement {
    }
    var HTMLTcsDropdownElement: {
        prototype: HTMLTcsDropdownElement;
        new (): HTMLTcsDropdownElement;
    };
    interface HTMLTcsEditorElement extends Components.TcsEditor, HTMLStencilElement {
    }
    var HTMLTcsEditorElement: {
        prototype: HTMLTcsEditorElement;
        new (): HTMLTcsEditorElement;
    };
    interface HTMLTcsIconElementEventMap {
        "clickIcon": SVGElement;
    }
    interface HTMLTcsIconElement extends Components.TcsIcon, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsIconElementEventMap>(type: K, listener: (this: HTMLTcsIconElement, ev: TcsIconCustomEvent<HTMLTcsIconElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsIconElementEventMap>(type: K, listener: (this: HTMLTcsIconElement, ev: TcsIconCustomEvent<HTMLTcsIconElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsIconElement: {
        prototype: HTMLTcsIconElement;
        new (): HTMLTcsIconElement;
    };
    interface HTMLTcsPopupElement extends Components.TcsPopup, HTMLStencilElement {
    }
    var HTMLTcsPopupElement: {
        prototype: HTMLTcsPopupElement;
        new (): HTMLTcsPopupElement;
    };
    interface HTMLTcsSelectElementEventMap {
        "selectChange": TcsSelectEntry|undefined;
    }
    interface HTMLTcsSelectElement extends Components.TcsSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsSelectElementEventMap>(type: K, listener: (this: HTMLTcsSelectElement, ev: TcsSelectCustomEvent<HTMLTcsSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsSelectElementEventMap>(type: K, listener: (this: HTMLTcsSelectElement, ev: TcsSelectCustomEvent<HTMLTcsSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsSelectElement: {
        prototype: HTMLTcsSelectElement;
        new (): HTMLTcsSelectElement;
    };
    interface HTMLTcsSettingsFormElementEventMap {
        "formChange": TcsSettingsFormValues;
        "formSubmit": TcsSettingsFormValues;
    }
    interface HTMLTcsSettingsFormElement extends Components.TcsSettingsForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsSettingsFormElementEventMap>(type: K, listener: (this: HTMLTcsSettingsFormElement, ev: TcsSettingsFormCustomEvent<HTMLTcsSettingsFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsSettingsFormElementEventMap>(type: K, listener: (this: HTMLTcsSettingsFormElement, ev: TcsSettingsFormCustomEvent<HTMLTcsSettingsFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsSettingsFormElement: {
        prototype: HTMLTcsSettingsFormElement;
        new (): HTMLTcsSettingsFormElement;
    };
    interface HTMLTcsStructureFormElementEventMap {
        "formChange": TcsStructureFormValues;
        "formSubmit": TcsStructureFormValues;
    }
    interface HTMLTcsStructureFormElement extends Components.TcsStructureForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsStructureFormElementEventMap>(type: K, listener: (this: HTMLTcsStructureFormElement, ev: TcsStructureFormCustomEvent<HTMLTcsStructureFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsStructureFormElementEventMap>(type: K, listener: (this: HTMLTcsStructureFormElement, ev: TcsStructureFormCustomEvent<HTMLTcsStructureFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsStructureFormElement: {
        prototype: HTMLTcsStructureFormElement;
        new (): HTMLTcsStructureFormElement;
    };
    interface HTMLTcsTextfieldElementEventMap {
        "textfieldChange": string;
    }
    interface HTMLTcsTextfieldElement extends Components.TcsTextfield, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsTextfieldElementEventMap>(type: K, listener: (this: HTMLTcsTextfieldElement, ev: TcsTextfieldCustomEvent<HTMLTcsTextfieldElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsTextfieldElementEventMap>(type: K, listener: (this: HTMLTcsTextfieldElement, ev: TcsTextfieldCustomEvent<HTMLTcsTextfieldElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsTextfieldElement: {
        prototype: HTMLTcsTextfieldElement;
        new (): HTMLTcsTextfieldElement;
    };
    interface HTMLTcsToolbarElementEventMap {
        "clickViewRaw": void;
        "clickUnclear": UnionUnclearReason;
        "clickReconstruction": UnionReconstructionReason;
        "clickAnnotation": void;
        "clickHighlighted": UnionHighlightedRend;
        "clickDeleted": UnionDeletedRend;
        "clickAbbreviation": UnionAbbreviationType;
        "clickPunctuation": string;
        "clickStructure": UnionStructureType|'anonymous-block';
        "clickBlankSpace": void;
        "clickRTL": void;
        "clickLTR": void;
        "clickTextSize": void;
        "clickLayout": void;
        "clickRemove": void;
        "clickSettings": void;
    }
    interface HTMLTcsToolbarElement extends Components.TcsToolbar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTcsToolbarElementEventMap>(type: K, listener: (this: HTMLTcsToolbarElement, ev: TcsToolbarCustomEvent<HTMLTcsToolbarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTcsToolbarElementEventMap>(type: K, listener: (this: HTMLTcsToolbarElement, ev: TcsToolbarCustomEvent<HTMLTcsToolbarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTcsToolbarElement: {
        prototype: HTMLTcsToolbarElement;
        new (): HTMLTcsToolbarElement;
    };
    interface HTMLTcsVisualizerElement extends Components.TcsVisualizer, HTMLStencilElement {
    }
    var HTMLTcsVisualizerElement: {
        prototype: HTMLTcsVisualizerElement;
        new (): HTMLTcsVisualizerElement;
    };
    interface HTMLElementTagNameMap {
        "tcs-annotation-form": HTMLTcsAnnotationFormElement;
        "tcs-blank-space-form": HTMLTcsBlankSpaceFormElement;
        "tcs-button": HTMLTcsButtonElement;
        "tcs-dropdown": HTMLTcsDropdownElement;
        "tcs-editor": HTMLTcsEditorElement;
        "tcs-icon": HTMLTcsIconElement;
        "tcs-popup": HTMLTcsPopupElement;
        "tcs-select": HTMLTcsSelectElement;
        "tcs-settings-form": HTMLTcsSettingsFormElement;
        "tcs-structure-form": HTMLTcsStructureFormElement;
        "tcs-textfield": HTMLTcsTextfieldElement;
        "tcs-toolbar": HTMLTcsToolbarElement;
        "tcs-visualizer": HTMLTcsVisualizerElement;
    }
}
declare namespace LocalJSX {
    interface TcsAnnotationForm {
        "onFormChange"?: (event: TcsAnnotationFormCustomEvent<TcsAnnotationFormValues>) => void;
        "onFormSubmit"?: (event: TcsAnnotationFormCustomEvent<TcsAnnotationFormValues>) => void;
    }
    interface TcsBlankSpaceForm {
        "onFormChange"?: (event: TcsBlankSpaceFormCustomEvent<TcsBlankSpaceFormValues>) => void;
        "onFormSubmit"?: (event: TcsBlankSpaceFormCustomEvent<TcsBlankSpaceFormValues>) => void;
    }
    interface TcsButton {
        "active"?: boolean;
        "disabled"?: boolean;
        "display"?: 'slim'|'default';
        "icon"?: UnionIcons;
        "iconOnly"?: boolean;
        "iconPosition"?: 'leading' | 'trailing';
        "onClickButton"?: (event: TcsButtonCustomEvent<HTMLDivElement>) => void;
        "outlined"?: boolean;
        "rotateOnActive"?: boolean;
        "rounded"?: boolean;
        "slimText"?: string;
        "stretched"?: boolean;
        "variation"?: 'default';
    }
    interface TcsDropdown {
        "config"?: DropdownConfig;
        "disabled"?: boolean;
        "display"?: 'slim'|'default';
        "slimText"?: string;
    }
    interface TcsEditor {
        "settings"?: EditorSettings;
        "toolbarConfig"?: ToolbarConfig;
    }
    interface TcsIcon {
        "icon"?: UnionIcons;
        "library"?: string;
        "onClickIcon"?: (event: TcsIconCustomEvent<SVGElement>) => void;
        "viewBox"?: string;
    }
    interface TcsPopup {
    }
    interface TcsSelect {
        "entries"?: TcsSelectEntry[];
        "inputId"?: string;
        "inputName"?: string;
        "onSelectChange"?: (event: TcsSelectCustomEvent<TcsSelectEntry|undefined>) => void;
        "placeholder"?: string;
        "required"?: boolean;
    }
    interface TcsSettingsForm {
        "defaultValues"?: TcsSettingsFormValues;
        "onFormChange"?: (event: TcsSettingsFormCustomEvent<TcsSettingsFormValues>) => void;
        "onFormSubmit"?: (event: TcsSettingsFormCustomEvent<TcsSettingsFormValues>) => void;
    }
    interface TcsStructureForm {
        "onFormChange"?: (event: TcsStructureFormCustomEvent<TcsStructureFormValues>) => void;
        "onFormSubmit"?: (event: TcsStructureFormCustomEvent<TcsStructureFormValues>) => void;
    }
    interface TcsTextfield {
        "allowedValues"?: (string|number)[];
        "defaultValue"?: string;
        "inputId"?: string;
        "inputName"?: string;
        "integer"?: boolean;
        "max"?: number;
        "min"?: number;
        "onTextfieldChange"?: (event: TcsTextfieldCustomEvent<string>) => void;
        "pattern"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: 'text'|'password'|'number'|'email';
    }
    interface TcsToolbar {
        "config"?: ToolbarConfig;
        "disabled"?: boolean;
        "layoutType"?: UnionLayoutType;
        "locked"?: boolean;
        "onClickAbbreviation"?: (event: TcsToolbarCustomEvent<UnionAbbreviationType>) => void;
        "onClickAnnotation"?: (event: TcsToolbarCustomEvent<void>) => void;
        "onClickBlankSpace"?: (event: TcsToolbarCustomEvent<void>) => void;
        "onClickDeleted"?: (event: TcsToolbarCustomEvent<UnionDeletedRend>) => void;
        "onClickHighlighted"?: (event: TcsToolbarCustomEvent<UnionHighlightedRend>) => void;
        "onClickLTR"?: (event: TcsToolbarCustomEvent<void>) => void;
        "onClickLayout"?: (event: TcsToolbarCustomEvent<void>) => void;
        "onClickPunctuation"?: (event: TcsToolbarCustomEvent<string>) => void;
        "onClickRTL"?: (event: TcsToolbarCustomEvent<void>) => void;
        "onClickReconstruction"?: (event: TcsToolbarCustomEvent<UnionReconstructionReason>) => void;
        "onClickRemove"?: (event: TcsToolbarCustomEvent<void>) => void;
        "onClickSettings"?: (event: TcsToolbarCustomEvent<void>) => void;
        "onClickStructure"?: (event: TcsToolbarCustomEvent<UnionStructureType|'anonymous-block'>) => void;
        "onClickTextSize"?: (event: TcsToolbarCustomEvent<void>) => void;
        "onClickUnclear"?: (event: TcsToolbarCustomEvent<UnionUnclearReason>) => void;
        "onClickViewRaw"?: (event: TcsToolbarCustomEvent<void>) => void;
        "textDirection"?: 'LTR'|'RTL';
        "viewRaw"?: boolean;
    }
    interface TcsVisualizer {
    }
    interface IntrinsicElements {
        "tcs-annotation-form": TcsAnnotationForm;
        "tcs-blank-space-form": TcsBlankSpaceForm;
        "tcs-button": TcsButton;
        "tcs-dropdown": TcsDropdown;
        "tcs-editor": TcsEditor;
        "tcs-icon": TcsIcon;
        "tcs-popup": TcsPopup;
        "tcs-select": TcsSelect;
        "tcs-settings-form": TcsSettingsForm;
        "tcs-structure-form": TcsStructureForm;
        "tcs-textfield": TcsTextfield;
        "tcs-toolbar": TcsToolbar;
        "tcs-visualizer": TcsVisualizer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tcs-annotation-form": LocalJSX.TcsAnnotationForm & JSXBase.HTMLAttributes<HTMLTcsAnnotationFormElement>;
            "tcs-blank-space-form": LocalJSX.TcsBlankSpaceForm & JSXBase.HTMLAttributes<HTMLTcsBlankSpaceFormElement>;
            "tcs-button": LocalJSX.TcsButton & JSXBase.HTMLAttributes<HTMLTcsButtonElement>;
            "tcs-dropdown": LocalJSX.TcsDropdown & JSXBase.HTMLAttributes<HTMLTcsDropdownElement>;
            "tcs-editor": LocalJSX.TcsEditor & JSXBase.HTMLAttributes<HTMLTcsEditorElement>;
            "tcs-icon": LocalJSX.TcsIcon & JSXBase.HTMLAttributes<HTMLTcsIconElement>;
            "tcs-popup": LocalJSX.TcsPopup & JSXBase.HTMLAttributes<HTMLTcsPopupElement>;
            "tcs-select": LocalJSX.TcsSelect & JSXBase.HTMLAttributes<HTMLTcsSelectElement>;
            "tcs-settings-form": LocalJSX.TcsSettingsForm & JSXBase.HTMLAttributes<HTMLTcsSettingsFormElement>;
            "tcs-structure-form": LocalJSX.TcsStructureForm & JSXBase.HTMLAttributes<HTMLTcsStructureFormElement>;
            "tcs-textfield": LocalJSX.TcsTextfield & JSXBase.HTMLAttributes<HTMLTcsTextfieldElement>;
            "tcs-toolbar": LocalJSX.TcsToolbar & JSXBase.HTMLAttributes<HTMLTcsToolbarElement>;
            "tcs-visualizer": LocalJSX.TcsVisualizer & JSXBase.HTMLAttributes<HTMLTcsVisualizerElement>;
        }
    }
}
